 -- Run this in Supabase Dashboard → SQL Editor → New query
-- (safe to run once on a fresh project)

-- 1. Profiles table — extends auth.users with an is_admin flag.
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  is_admin boolean not null default false,
  created_at timestamptz default now()
);

alter table profiles enable row level security;

create policy "Users can read their own profile" on profiles
  for select using (auth.uid() = id);

-- Auto-create a profile row whenever someone signs up.
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email) values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. Products — readable by everyone, writable only by admins.
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  image_url text not null,
  created_at timestamptz default now()
);

alter table products enable row level security;

create policy "Anyone can read products" on products
  for select using (true);

create policy "Only admins can insert products" on products
  for insert with check (
    exists (select 1 from profiles where id = auth.uid() and is_admin = true)
  );

create policy "Only admins can delete products" on products
  for delete using (
    exists (select 1 from profiles where id = auth.uid() and is_admin = true)
  );

-- 3. Cart items — each user can only see/edit their own.
create table if not exists cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  product_id bigint references products not null,
  quantity int not null default 1,
  created_at timestamptz default now(),
  unique (user_id, product_id)
);

alter table cart_items enable row level security;

create policy "Users manage their own cart" on cart_items
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 4. Orders + order_items — for the invoice, created at checkout (no payment).
create table if not exists orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  total numeric not null,
  created_at timestamptz default now()
);

alter table orders enable row level security;

create policy "Users manage their own orders" on orders
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders on delete cascade not null,
  product_name text not null,
  price numeric not null,
  quantity int not null
);

alter table order_items enable row level security;

create policy "Users manage their own order items" on order_items
  for all using (
    exists (select 1 from orders where orders.id = order_id and orders.user_id = auth.uid())
  ) with check (
    exists (select 1 from orders where orders.id = order_id and orders.user_id = auth.uid())
  );

-- 5. Seed starter products.
insert into products (name, price, image_url) values
  ('Bananas (6pc)', 49.0, 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400'),
  ('Amul Milk 1L', 66.0, 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400'),
  ('Bread Loaf', 45.0, 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400'),
  ('Eggs (6pc)', 42.0, 'https://images.unsplash.com/photo-1518569656558-1f25e69d93d7?w=400'),
  ('Tomatoes 1kg', 30.0, 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=400');

-- Additional products for the Chocolates, Electronics, and Juices categories.
insert into products (name, price, image_url)
select seed.name, seed.price, seed.image_url
from (values
  ('Dark Chocolate  Amul 150g', 120.0, 'https://images.unsplash.com/photo-1548907040-4d42bfcf8f4c?w=400'),
  ('Milk Chocolate Bar 100g', 85.0, 'https://images.unsplash.com/photo-1575377427642-087cf684f29d?w=400'),
  ('Chocolate Cookies Pack', 99.0, 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400'),
  ('Wireless Headphones', 1299.0, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400'),
  ('Smartphone Stand', 399.0, 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400'),
  ('USB-C Fast Charger', 699.0, 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400'),
  ('Mango Juice 1L', 110.0, 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400'),
  ('Orange Juice 1L', 125.0, 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400'),
  ('Mixed Fruit Juice', 135.0, 'https://images.unsplash.com/photo-1546173159-315724a31696?w=400')
) as seed(name, price, image_url)
where not exists (
  select 1 from products existing where existing.name = seed.name
);

-- 6. AFTER you've signed up your own account in the app, run this once
-- (replace the email) to make that account an admin:
-- update profiles set is_admin = true where email = 'your-email@example.com';
