create table if not exists users (
  id uuid primary key,
  email text not null unique,
  password_hash text not null,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12, 2) not null check (price >= 0),
  image_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references users(id) on delete cascade,
  product_id bigint not null references products(id),
  quantity integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references users(id),
  total numeric(12, 2) not null check (total >= 0),
  created_at timestamptz not null default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  product_name text not null,
  price numeric(12, 2) not null check (price >= 0),
  quantity integer not null check (quantity > 0)
);